<a href="https://colab.research.google.com/github/electroniccity765-png/FOODIE-EXPRESS/blob/main/(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]
           ])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c=np.array([
    [
        [1,2],
        [2,3]
    ],
    [
        [3,4],
        [6,7]
    ],

])
print(c)

[[[1 2]
  [2 3]]

 [[3 4]
  [6 7]]]


In [ ]:
d=np.zeros([3,4])
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d=np.ones([5,6])
print(d)


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
d=np.full([7,8],9)
print(d)

[[9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]]


In [ ]:
a=np.ones([2,3])
print(a)
b=np.zeros([3,4])
print(b)
c=np.full([4,5],7)
print(c)
d=np.eye(4)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.linspace(2,10,12)

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [ ]:
# uniform Rndom[0,1]
np.random.randn(9,3)

array([[-0.22006169, -1.67033609,  1.00399953],
       [-1.61278159,  0.0107429 ,  0.60461588],
       [-1.74137713, -0.4027339 ,  0.05218537],
       [-2.10066885,  0.33171073, -0.44173497],
       [ 1.07687546,  0.84862815, -1.43292913],
       [-0.46308268,  0.02166604, -0.40569303],
       [-0.33253677,  1.89195317, -0.22745732],
       [ 0.52836272, -1.14673316,  1.06663394],
       [ 0.15320692,  0.27151508, -0.57622149]])

In [ ]:
# random integer
np.random.randint(2,10,5)

array([4, 3, 2, 7, 2])

In [ ]:
np.empty((3,5))

array([[4.20069440e-315, 0.00000000e+000, 8.99948104e-008,
        6.01346953e-154, 1.20480715e+132],
       [2.65981967e-260, 6.01347002e-154, 6.98347712e-077,
        6.01346953e-154, 8.94213159e+130],
       [2.65981966e-260, 6.01347002e-154, 2.99938058e-067,
        2.42761679e-154, 1.26480805e-321]])

In [ ]:
arr= np.array(["a","b","c","d","e"])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


(5,)
1
5
<U1
4
20


In [ ]:
a=np.array([1,23,4,5,7,7,6])
print(a[0])
print(a[2])
print(a[-1])
print(a[1:4])
print(a[:3])
print(a[::2])
print(a[::-1])

1
4
6
[23  4  5]
[ 1 23  4]
[1 4 7 6]
[ 6  7  7  5  4 23  1]


In [ ]:
m = np.array([[4,5,6],
             [7,8,9]])
print(m[0,0])
print(m[1,2])
print(m[0,1:3])
print(m[0,2])
print(m[0:2,2])
print(m[0:2,1:3])

4
9
[5 6]
6
[6 9]
[[5 6]
 [8 9]]


In [ ]:
x=np.array([6,7])

In [ ]:
x=np.array([[4,5,67,81,1,1,1,23,54]])
mask=x>50
print(x[mask])
print(x[x>15])

[67 81 54]
[67 81 23 54]


In [ ]:
a=np.arrray([])

In [ ]:
a=np.array([2,4,6,8,10,12,14,16,18,20])
print(a)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
arr=np.arange(2,21,2)
print(arr)
print(np.max(arr))
print(np.argmax(arr))

[ 2  4  6  8 10 12 14 16 18 20]
20
9


In [ ]:
import numpy as np
arr = np.eye(5).reshape(5, 5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr